active: "testnet"

mainnet:
  node: 
    rpc_node: "" # tcp://dataseed1.binance.org:80
    accelerated_node: "" # https://dex-asiapacific.binance.org/api/v1
    api_server_endpoint: ""
    explorer_api_endpoint: "" # https://explorer.binance.org/api/v1
  database:
    host: "127.0.0.1"
    port: 5432
    user: "postgres"
    password: "admin"
    table: ""
  web:
    port: 5000
  market:
    coingecko_endpoint: ""

testnet:
  node: 
    rpc_node: "tcp://192.168.3.100:26657"
    accelerated_node: "tcp://192.168.3.100:26657"
    api_server_endpoint: "http://192.168.3.100:8545"
    explorer_api_endpoint: "tcp://192.168.3.100:26657"
  database:
    host: "127.0.0.1"
    port: 5432
    user: "postgres"
    password: "admin"
    table: ""
  web:
    port: 5000
  market:
    coingecko_endpoint: ""
